import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { gunzipSync } from 'node:zlib';
import { spawnSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';

const rustName = name => name.split(/[^a-zA-Z0-9]+/).filter(Boolean).map(s => s[0].toUpperCase() + s.slice(1)).join('');
const fieldName = name => ['type', 'ref', 'self', 'match', 'where', 'loop', 'in'].includes(name) ? `r#${name}` : name;

/** Translate only the converter's declared types; unconstrained schemas remain JSON values. */
export function generate(schemas) {
  const definitions = new Map();
  function type(schema, name) {
    let result;
    if (schema.$ref) {
      const key = schema.$ref.replace('#/components/schemas/', '');
      if (!(key in schemas)) throw new Error(`Unknown reference: ${schema.$ref}`);
      result = rustName(key);
    } else if (schema.enum && schema.type === 'string') {
      result = name;
      definitions.set(name, `#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]\npub enum ${name} {\n${schema.enum.map((v, i) => `    #[serde(rename = ${JSON.stringify(v)})]\n    Value${i},`).join('\n')}\n}\n`);
    } else if (schema.type === 'object' && schema.properties) {
      result = name;
      const fields = Object.entries(schema.properties).map(([field, value]) => {
        const required = schema.required?.includes(field);
        const inner = type(value, name + rustName(field));
        const fieldType = required ? inner : `Option<${inner}>`;
        const attrs = required
          ? '    #[serde(deserialize_with = "required")]\n'
          : '    #[serde(default, skip_serializing_if = "Option::is_none", deserialize_with = "present")]\n';
        return `    #[serde(rename = ${JSON.stringify(field)})]\n${attrs}    pub ${fieldName(field)}: ${fieldType},`;
      });
      fields.push('    #[serde(flatten)]\n    pub extra: std::collections::BTreeMap<String, Value>,');
      definitions.set(name, `#[derive(Clone, Debug, Deserialize, Serialize)]\npub struct ${name} {\n${fields.join('\n')}\n}\n`);
    } else if (schema.type === 'array') {
      result = `Vec<${type(schema.items ?? {}, name + 'Item')}>`;
    } else if (schema.type === 'object') {
      result = `std::collections::BTreeMap<String, ${type(typeof schema.additionalProperties === 'object' ? schema.additionalProperties : {}, name + 'Value')}>`;
    } else {
      result = { string: 'String', boolean: 'bool', integer: 'i64', number: 'f64' }[schema.type];
      if (!result) {
        if (schema.type || schema.oneOf || schema.anyOf || schema.allOf) throw new Error(`Unsupported schema: ${JSON.stringify(schema)}`);
        result = 'Value';
      }
    }
    return schema.nullable ? `Nullable<${result}>` : result;
  }
  for (const [key, schema] of Object.entries(schemas)) {
    const name = rustName(key);
    const representation = type({ ...schema, nullable: false }, name);
    if (schema.nullable && representation === name) {
      const definition = definitions.get(name);
      definitions.delete(name);
      definitions.set(name + 'Object', definition.replace(`pub struct ${name} {`, `pub struct ${name}Object {`));
      definitions.set(name, `pub type ${name} = Nullable<${name}Object>;\n`);
    } else if (representation !== name || schema.nullable) {
      definitions.set(name, `pub type ${name} = ${schema.nullable ? `Nullable<${representation}>` : representation};\n`);
    }
  }
  return `// Generated by scripts/generate-api.mjs from Canonical's converter. Do not edit.\n#![allow(dead_code)]\nuse serde::{Deserialize, Serialize};\nuse serde_json::Value;\n\n#[derive(Clone, Debug, PartialEq, Deserialize, Serialize)]\n#[serde(untagged)]\npub enum Nullable<T> {\n    Value(T),\n    Null,\n}\n\nfn required<'de, D, T>(deserializer: D) -> Result<T, D::Error>\nwhere\n    D: serde::Deserializer<'de>,\n    T: Deserialize<'de>,\n{\n    T::deserialize(deserializer)\n}\n\nfn present<'de, D, T>(deserializer: D) -> Result<Option<T>, D::Error>\nwhere\n    D: serde::Deserializer<'de>,\n    T: Deserialize<'de>,\n{\n    T::deserialize(deserializer).map(Some)\n}\n\n` + [...definitions.values()].join('\n') + '\n' + `pub fn validate_component(name: &str, value: Value) -> Result<(), serde_json::Error> {\n    match name {\n${Object.keys(schemas).map(key => `        ${JSON.stringify(key)} => serde_json::from_value::<${rustName(key)}>(value).map(|_| ()),`).join('\n')}\n        _ => Err(<serde_json::Error as serde::de::Error>::custom("unknown component schema")),\n    }\n}\n`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const bytes = gunzipSync(await readFile(new URL('../openapi/launchpad.json.gz', import.meta.url)));
  const provenance = JSON.parse(await readFile(new URL('../openapi/provenance.json', import.meta.url)));
  if (createHash('sha256').update(bytes).digest('hex') !== provenance.sha256) throw new Error('OpenAPI snapshot does not match provenance');
  const spec = JSON.parse(bytes);
  const source = generate(spec.components.schemas);
  const formatted = spawnSync('rustfmt', ['--edition', '2024'], { input: source, encoding: 'utf8', maxBuffer: 10 * 1024 * 1024 });
  if (formatted.status !== 0) throw new Error(formatted.stderr);
  const destination = new URL('../src/generated.rs', import.meta.url);
  if (process.argv.includes('--check')) {
    if (await readFile(destination, 'utf8') !== formatted.stdout) throw new Error('Generated API types are stale: run npm run generate');
  } else {
    await writeFile(destination, formatted.stdout);
  }
}
